name: locationprojectflutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  latlong: ^0.6.1
  google_maps_flutter: ^0.5.26
  location: ^3.0.2
  geolocator: ^5.1.3
  http: ^0.12.0+2
  url_launcher: ^5.4.2
  shared_preferences: ^0.5.6+3
  sqflite: ^1.3.0
  cached_network_image: ^2.2.0
  flutter_slidable: ^0.5.4
  share: ^0.5.3
  grouped_buttons: ^1.0.4
  firebase_auth: ^0.16.0
  auto_animated: ^2.1.0
  flutter_geofence: ^0.2.0
  flutter_local_notifications: ^1.4.3
  cloud_firestore: ^0.13.5
  provider: ^4.0.5+1
#  flutter_mobx: ^1.1.0
#  mobx: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  mockito: ^4.1.1
  flutter_launcher_icons: ^0.7.4
#  build_runner: ^1.8.1
#  mobx_codegen: ^1.0.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png