name: locationprojectflutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  latlong: ^0.6.1
  google_maps_flutter: ^0.5.26
  location: ^3.0.2
  geolocator: ^5.1.3
  http: ^0.12.0+2
  url_launcher: ^5.4.2
  shared_preferences: ^0.5.6+3
  sqflite: ^1.3.0
  cached_network_image: ^2.2.0
  slide_item: ^1.0.7
  share: ^0.5.3
  grouped_buttons: ^1.0.4
  firebase_auth: ^0.16.0
  provider: ^4.0.5+1
  slim: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png