name: locationprojectflutter
description: A new Flutter application.

version: 1.0.0+51

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  latlong: ^0.6.1
  google_maps_flutter: ^0.5.26
  location: ^3.0.2
  http: ^0.12.0+2
  shared_preferences: ^0.5.6+3
  sqflite: ^1.3.0
  cached_network_image: ^2.2.0
  flutter_slidable: ^0.5.4
  share: ^0.5.3
  grouped_buttons: ^1.0.4
  fluttertoast: ^3.1.3
  chewie: ^0.9.10
  image_picker: ^0.6.7+2
  photo_view: ^0.5.0
  intl: ^0.16.1
  firebase_auth: ^0.18.2
  cloud_firestore: ^0.14.2
  firebase_messaging: ^7.0.3
  firebase_storage: ^4.0.1
  firebase_core: ^0.5.1
  google_sign_in: ^4.5.5
  flutter_facebook_login: ^3.0.0
  auto_animated: ^2.1.0
  map_launcher: ^0.4.5
  flutter_geofence: ^0.4.0
  flutter_local_notifications: ^1.4.3
  flutter_stories: ^0.2.1+1
  simple_image_crop: ^0.1.3
  path_provider: ^1.1.0
  audioplayers: ^0.13.2
  audioplayer: ^0.8.1
  flutter_audio_recorder: ^0.5.5
  permission_handler: ^3.0.0
  agora_rtc_engine: ^1.0.13
  chips_choice: ^1.4.1
  flutter_svg: ^0.18.1
  provider: ^4.0.5+1
#  get_it: ^3.1.0
#  dio: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  mockito: ^4.1.1
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/google_icon.png
    - assets/img_not_available.jpeg
    - assets/mimi1.gif
    - assets/mimi2.gif
    - assets/mimi3.gif
    - assets/mimi4.gif
    - assets/mimi5.gif
    - assets/facebook_icon.jpg
    - assets/phone_icon.jpg
    - assets/icon_type_list_unselected.svg
    - assets/icon_type_list_selected.svg
    - assets/icon_type_grid_unselected.svg
    - assets/icon_type_grid_selected.svg